name: spring_moving_cursor
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.8.1 <3.0.0"
dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # state management
  state_notifier: any
  hooks_riverpod: any
  flutter_hooks: any
  subscription_holder: any
  rxdart: any
  # ui
  animations: any
  gap: any
  mono_kit: any
  adaptive_dialog: ^0.7.5+3
  # Firebase
#  firestore_ref: any
#  firebase_auth: any
#  cloud_firestore: any
#  firebase_messaging: any
#  firebase_analytics: any
#  firebase_storage: any
  trotter:

  freezed_annotation: any
  functional_widget_annotation: any
dev_dependencies:
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter
  functional_widget:  ^0.8.0
  freezed: any
  json_serializable: any
  pedantic_mono: any
  intl_translation: any
flutter:
  uses-material-design: true
